// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: myproto.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloRes) Reset() {
	*x = HelloRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myproto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRes) ProtoMessage() {}

func (x *HelloRes) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRes.ProtoReflect.Descriptor instead.
func (*HelloRes) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NameReq) Reset() {
	*x = NameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myproto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameReq) ProtoMessage() {}

func (x *NameReq) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameReq.ProtoReflect.Descriptor instead.
func (*NameReq) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{2}
}

func (x *NameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *NameRes) Reset() {
	*x = NameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myproto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRes) ProtoMessage() {}

func (x *NameRes) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRes.ProtoReflect.Descriptor instead.
func (*NameRes) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{3}
}

func (x *NameRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_myproto_proto protoreflect.FileDescriptor

var file_myproto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x07, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x6e, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x11, 0x2e,
	0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x53, 0x61, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myproto_proto_rawDescOnce sync.Once
	file_myproto_proto_rawDescData = file_myproto_proto_rawDesc
)

func file_myproto_proto_rawDescGZIP() []byte {
	file_myproto_proto_rawDescOnce.Do(func() {
		file_myproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_myproto_proto_rawDescData)
	})
	return file_myproto_proto_rawDescData
}

var file_myproto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_myproto_proto_goTypes = []interface{}{
	(*HelloReq)(nil), // 0: myproto.HelloReq
	(*HelloRes)(nil), // 1: myproto.HelloRes
	(*NameReq)(nil),  // 2: myproto.NameReq
	(*NameRes)(nil),  // 3: myproto.NameRes
}
var file_myproto_proto_depIdxs = []int32{
	0, // 0: myproto.Helloserver.Sayhello:input_type -> myproto.HelloReq
	2, // 1: myproto.Helloserver.Sayname:input_type -> myproto.NameReq
	1, // 2: myproto.Helloserver.Sayhello:output_type -> myproto.HelloRes
	3, // 3: myproto.Helloserver.Sayname:output_type -> myproto.NameRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myproto_proto_init() }
func file_myproto_proto_init() {
	if File_myproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myproto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myproto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myproto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myproto_proto_goTypes,
		DependencyIndexes: file_myproto_proto_depIdxs,
		MessageInfos:      file_myproto_proto_msgTypes,
	}.Build()
	File_myproto_proto = out.File
	file_myproto_proto_rawDesc = nil
	file_myproto_proto_goTypes = nil
	file_myproto_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloserverClient is the client API for Helloserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloserverClient interface {
	Sayhello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
	Sayname(ctx context.Context, in *NameReq, opts ...grpc.CallOption) (*NameRes, error)
}

type helloserverClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloserverClient(cc grpc.ClientConnInterface) HelloserverClient {
	return &helloserverClient{cc}
}

func (c *helloserverClient) Sayhello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	out := new(HelloRes)
	err := c.cc.Invoke(ctx, "/myproto.Helloserver/Sayhello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloserverClient) Sayname(ctx context.Context, in *NameReq, opts ...grpc.CallOption) (*NameRes, error) {
	out := new(NameRes)
	err := c.cc.Invoke(ctx, "/myproto.Helloserver/Sayname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloserverServer is the server API for Helloserver service.
type HelloserverServer interface {
	Sayhello(context.Context, *HelloReq) (*HelloRes, error)
	Sayname(context.Context, *NameReq) (*NameRes, error)
}

// UnimplementedHelloserverServer can be embedded to have forward compatible implementations.
type UnimplementedHelloserverServer struct {
}

func (*UnimplementedHelloserverServer) Sayhello(context.Context, *HelloReq) (*HelloRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sayhello not implemented")
}
func (*UnimplementedHelloserverServer) Sayname(context.Context, *NameReq) (*NameRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sayname not implemented")
}

func RegisterHelloserverServer(s *grpc.Server, srv HelloserverServer) {
	s.RegisterService(&_Helloserver_serviceDesc, srv)
}

func _Helloserver_Sayhello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloserverServer).Sayhello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myproto.Helloserver/Sayhello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloserverServer).Sayhello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloserver_Sayname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloserverServer).Sayname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myproto.Helloserver/Sayname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloserverServer).Sayname(ctx, req.(*NameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Helloserver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myproto.Helloserver",
	HandlerType: (*HelloserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sayhello",
			Handler:    _Helloserver_Sayhello_Handler,
		},
		{
			MethodName: "Sayname",
			Handler:    _Helloserver_Sayname_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myproto.proto",
}
